name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: evilz-agent
          template: classic
          filename: github-metrics.svg
          base: header,activity,community,repositories
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_details: bytes-size,percentage
          plugin_languages_limit: 8
          plugin_followup: yes
